### HOMEWORK - ASSIGNMENT 9 - HMM
### BY SOURITA NAG AND SARAH RUCKMAN

In [2]:
pip install --upgrade --user hmmlearn

Note: you may need to restart the kernel to use updated packages.


In [188]:
import pandas as pd
import numpy as np
from hmmlearn import hmm
import torch

### Problem 1

In [189]:
dice_rolls = pd.read_csv('C:/Users/Sourita Nag/Downloads/hmm_pb1.csv',header=None)
x = np.array(dice_rolls)[0]
x

array([6, 2, 2, 3, 1, 5, 3, 6, 3, 4, 1, 3, 1, 5, 6, 3, 5, 2, 4, 5, 4, 3,
       2, 3, 3, 3, 4, 5, 3, 3, 1, 1, 2, 2, 4, 6, 6, 3, 2, 5, 5, 5, 5, 1,
       5, 3, 2, 1, 5, 2, 1, 4, 6, 4, 5, 1, 6, 4, 5, 1, 5, 5, 2, 6, 4, 6,
       4, 5, 2, 3, 1, 6, 6, 6, 2, 6, 6, 6, 5, 3, 6, 3, 1, 6, 6, 6, 6, 5,
       4, 6, 4, 6, 6, 6, 6, 6, 6, 5, 1, 6, 6, 4, 6, 3, 6, 6, 4, 2, 1, 5,
       2, 6, 4, 6, 6, 6, 2, 6, 3, 6, 3, 4, 1, 4, 2, 1, 5, 3, 4, 3, 4, 1,
       6, 5, 5, 5, 3, 4, 4, 4, 2, 2, 3, 2, 5, 6, 1, 4, 1, 5, 6, 1, 6, 1,
       6, 6, 6, 6, 6, 6, 2, 3, 2, 1, 2, 6, 6, 4, 5, 6, 6, 6, 6, 6, 4, 6,
       3, 3, 6, 6, 5, 6, 6, 6, 6, 6, 6, 1, 6, 6, 4, 6, 4, 6, 5, 5, 3, 2,
       4, 6, 6, 6, 1, 6, 6, 6, 1, 4, 6, 6, 3, 2, 5, 3, 4, 2, 2, 5, 5, 6,
       1, 2, 1, 3, 2, 6, 1, 1, 4, 5, 2, 2, 3, 3, 6, 6, 6, 2, 4, 1, 6, 5,
       6, 6, 5, 6, 2, 4, 6, 6, 6, 6, 4, 6, 2, 6, 6, 6, 4, 6, 6, 4, 6, 6,
       6, 4, 6, 4, 6, 5, 5, 6, 6, 4, 6, 6, 6, 1, 4, 6, 3, 2, 5, 4, 4, 4,
       1, 3, 3, 2, 5, 6, 2, 5, 1, 6, 1, 4, 3, 5], d

In [190]:
#Transition probs
a_k = torch.tensor([[0.95,0.05],[0.05,0.95]])

#Start probs
pi_k = torch.tensor([0.5,0.5])
pi_k.shape

#Emission probs
b_k = torch.tensor([[1/6,1/6,1/6,1/6,1/6,1/6],[1/10,1/10,1/10,1/10,1/10,1/2]])
b_k.shape

torch.Size([2, 6])

### Part a - Viterbi Algorithm

In [191]:
C_k = torch.zeros(2,x.size)
P_tr_k = torch.zeros(2,x.size)
C_k[:,0] = torch.log(b_k[:,x[1]]*pi_k)
for t in range(1,x.size):
    for k in range(2):
        max_val = torch.log(a_k[:,k]) + C_k[:,t-1]
        C_k[k,t] = torch.log(b_k[k,x[t]-1]) + torch.max(max_val)
        P_tr_k[k,t] = torch.argmax(max_val)
P = torch.exp(torch.max(C_k,1).values)
y=torch.ones(x.size).long()
y[x.size-1]=torch.argmax(C_k[:,x.size-1]) + 1

for t in range(x.size-1,0,-1):
    y[t-1]=P_tr_k[y[t]-1,t] + 1
y

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

### Part b - Forward and Backward 

In [192]:
#Forward algorithm
alpha_k = torch.zeros(2,x.size)
alpha_k[:,0] = b_k[:,x[1]]*pi_k
alpha_k[:,0]

for t in range(1,x.size):
    alpha_k[:,t] = b_k[:,x[t]-1]*torch.sum(a_k@alpha_k[:,t-1])
    u = -min(torch.floor(torch.log10(alpha_k[:,t])))
    alpha_k[:,t] = alpha_k[:,t]*(10**u)
alpha_k.shape

torch.Size([2, 300])

In [193]:
#alpha_k

In [194]:
#Reporting the results
alpha_138 = alpha_k[0,138]/alpha_k[1,138]
print(f'The ratio of alpha 138 is given as {alpha_138}')

The ratio of alpha 138 is given as 1.666666865348816


In [195]:
#Backward algorithm
beta_k = torch.zeros(2,x.size)
beta_k[:,-1] = 1

for t in range(x.size-2,-1,-1):
    for k in range(2):
        
        beta_k[k,t] = torch.sum(a_k[k,:]*beta_k[:,t+1]*b_k[:,x[t+1]-1])
        u = -(torch.floor(torch.log10(beta_k[k,t])))
        beta_k[k,t] = beta_k[k,t]*(10**u)

In [196]:
#beta_k

In [197]:
#Reporting the results
beta_138 = beta_k[0,138]/beta_k[1,138]
print(f'The ratio of beta 138 is given as {beta_138}')

The ratio of beta 138 is given as 0.2867904007434845


### Problem 2 - Baum Welch Using package

In [198]:
x2 =  pd.read_csv('C:/Users/Sourita Nag/Downloads/hmm_pb2.csv',delimiter =',',header=None)
x2 = np.array(x2)[0]
x2.shape

(20000,)

In [199]:
x2

array([3, 1, 5, ..., 2, 3, 4], dtype=int64)

In [200]:
#Executing baum Welch inbuilt package has been used
pi = pi_k.clone()
a = a_k.clone()
b = b_k.clone()

model = hmm.CategoricalHMM(n_components=2, random_state=7)
model.startprob_ = pi
model.transmat_ = a
model.emissionprob_ = b

fitted_model = model.fit(x2.reshape(-1,1))

#The different probs are
print(f'The start probabilities is {fitted_model.startprob_}\n')
print(f'The transition probabilities is {fitted_model.transmat_}\n')
print(f'The emission probabilities is {fitted_model.emissionprob_}\n')

Even though the 'startprob_' attribute is set, it will be overwritten during initialization because 'init_params' contains 's'
Even though the 'transmat_' attribute is set, it will be overwritten during initialization because 'init_params' contains 't'
Even though the 'emissionprob_' attribute is set, it will be overwritten during initialization because 'init_params' contains 'e'


The start probabilities is [1.80111513e-04 9.99819888e-01]

The transition probabilities is [[0.15447447 0.84552553]
 [0.65837945 0.34162055]]

The emission probabilities is [[0.         0.21097839 0.13518022 0.15214845 0.16723426 0.10765913
  0.22679956]
 [0.         0.14138413 0.19248674 0.18407731 0.21999813 0.14143654
  0.12061715]]

